import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

DOCUMENTS_S3_KEY = "documents.s3_key"
PROJECT_ACCESSES_PROJECT_ID = "project_accesses.project_id"
PROJECT_ACCESSES_USER_ID = "project_accesses.user_id"
PROJECT_REPORT_PROJECT_ID = "project_report.project_id"
DOCUMENTS_ID = "documents.id"
PROJECT_ACCESSES_ID = "project_accesses.id"
PROJECT_REPORT_ID = "project_report.id"
PROJECTS_ID = "projects.id"
USERS_ID = "users.id"
USERS_LOGIN = "users.login"

"""add project_report table

Revision ID: b503171e1db5
Revises: 37025df8efa9
Create Date: 2025-11-01 20:36:51.725501
"""

revision = "b503171e1db5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_id"), "users", [USERS_ID.split(".")[1]], unique=False
    )
    op.create_index(
        op.f("ix_users_login"),
        "users",
        [USERS_LOGIN.split(".")[1]],
        unique=True,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            [PROJECTS_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            [PROJECTS_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(DOCUMENTS_S3_KEY.split(".")[1]),
    )
    op.create_index(
        op.f("ix_documents_id"),
        "documents",
        [DOCUMENTS_ID.split(".")[1]],
        unique=False,
    )
    op.create_table(
        "project_accesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("granted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            [PROJECTS_ID],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [USERS_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            PROJECT_ACCESSES_PROJECT_ID.split(".")[1],
            PROJECT_ACCESSES_USER_ID.split(".")[1],
            name="_project_user_uc",
        ),
    )
    op.create_index(
        op.f("ix_project_accesses_id"),
        "project_accesses",
        [PROJECT_ACCESSES_ID.split(".")[1]],
        unique=False,
    )
    op.create_table(
        "project_report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("total_size", sa.BigInteger(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            [PROJECTS_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(PROJECT_REPORT_PROJECT_ID.split(".")[1]),
    )
    op.create_index(
        op.f("ix_project_report_id"),
        "project_report",
        [PROJECT_REPORT_ID.split(".")[1]],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_report_id"), table_name="project_report")
    op.drop_table("project_report")
    op.drop_index(
        op.f("ix_project_accesses_id"), table_name="project_accesses"
    )
    op.drop_table("project_accesses")
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_login"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
